const FormData = require('form-data');
const fetch = require('node-fetch');

exports.handler = async function(event, context) {
  // Set CORS headers
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json'
  };

  // Handle preflight
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers,
      body: ''
    };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }

  try {
    const { type = 'image', imageBase64, sourceAge, targetAge, duration = 5, fps = 24 } = JSON.parse(event.body);
    
    if (!imageBase64 || sourceAge === undefined || targetAge === undefined) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing required parameters' })
      };
    }

    console.log(`[age] Request: ${sourceAge} → ${targetAge}, type: ${type}`);
    
    // Convert base64 to buffer
    const buffer = Buffer.from(imageBase64, 'base64');
    const form = new FormData();
    form.append('files', buffer, { 
      filename: 'image.jpg', 
      contentType: 'image/jpeg' 
    });

    // Upload image with retry
    let uploadData;
    let uploadAttempt = 0;
    const maxUploadRetries = 2;
    
    while (uploadAttempt < maxUploadRetries) {
      try {
        console.log(`[age] Upload attempt ${uploadAttempt + 1}/${maxUploadRetries}`);
        
        const uploadRes = await fetch(
          'https://robys01-face-aging.hf.space/gradio_api/upload',
          {
            method: 'POST',
            body: form,
            headers: form.getHeaders(),
            timeout: 30000
          }
        );
        
        uploadData = await uploadRes.json();
        
        if (uploadRes.status === 200 && Array.isArray(uploadData) && uploadData.length > 0) {
          console.log('[age] Upload successful:', uploadData[0]);
          break;
        }
        
        console.warn(`[age] Upload failed (attempt ${uploadAttempt + 1}):`, uploadData);
        uploadAttempt++;
        
        if (uploadAttempt < maxUploadRetries) {
          await new Promise(resolve => setTimeout(resolve, 2000)); // Wait 2s before retry
        }
      } catch (uploadError) {
        console.error(`[age] Upload error (attempt ${uploadAttempt + 1}):`, uploadError.message);
        uploadAttempt++;
        
        if (uploadAttempt >= maxUploadRetries) {
          throw new Error(`Upload failed after ${maxUploadRetries} attempts: ${uploadError.message}`);
        }
        
        await new Promise(resolve => setTimeout(resolve, 2000));
      }
    }
    
    if (!uploadData || !Array.isArray(uploadData) || uploadData.length === 0) {
      throw new Error('Upload failed - no file path returned');
    }
    
    const filePath = uploadData[0];

    // Call predict endpoint with timeout handling
    let predictRes;
    const predictUrl = type === 'video' 
      ? 'https://robys01-face-aging.hf.space/gradio_api/run/predict_1'
      : 'https://robys01-face-aging.hf.space/gradio_api/run/predict';
    
    const predictBody = type === 'video'
      ? {
          data: [
            { path: filePath },
            0,
            Number(targetAge),
            Number(duration),
            Number(fps)
          ]
        }
      : {
          data: [
            { path: filePath },
            Number(sourceAge),
            Number(targetAge)
          ]
        };
    
    console.log(`[age] Calling predict endpoint...`);
    
    try {
      predictRes = await fetch(predictUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(predictBody),
        timeout: 90000 // 90 seconds for AI processing
      });
    } catch (fetchError) {
      console.error('[age] Predict fetch error:', fetchError.message);
      throw new Error(`Prediction request failed: ${fetchError.message}`);
    }

    if (!predictRes.ok) {
      const errorText = await predictRes.text();
      console.error('[age] Predict HTTP error:', predictRes.status, errorText);
      throw new Error(`Prediction failed with status ${predictRes.status}`);
    }

    let predictData;
    try {
      predictData = await predictRes.json();
    } catch (jsonError) {
      console.error('[age] Failed to parse prediction response:', jsonError.message);
      throw new Error('Invalid response from AI service');
    }

    if (predictData.error) {
      console.error('[age] Prediction error:', predictData.error);
      throw new Error(`AI error: ${predictData.error}`);
    }
    
    if (!predictData.data || predictData.data.length === 0) {
      console.error('[age] No data in prediction response');
      throw new Error('No output generated by AI');
    }

    // Extract output URL
    let outputUrl;
    if (type === 'video') {
      const videoData = predictData.data[0];
      outputUrl = videoData?.video?.url || videoData?.url || videoData;
      if (typeof outputUrl === 'string' && !outputUrl.startsWith('http')) {
        outputUrl = 'https://robys01-face-aging.hf.space/gradio_api/file=' + outputUrl;
      }
    } else {
      const imageData = predictData.data[0];
      outputUrl = imageData.url || 
                  (imageData.path ? 'https://robys01-face-aging.hf.space/gradio_api/file=' + imageData.path : null);
    }

    if (!outputUrl) {
      console.error('[age] No output URL in response:', predictData);
      throw new Error('No output URL generated');
    }

    console.log('[age] Success:', outputUrl.substring(0, 80) + '...');

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ output: outputUrl })
    };

  } catch (error) {
    console.error('[age] Request failed:', error.message);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ 
        error: error.message || 'Processing failed',
        details: 'The AI service may be overloaded or sleeping. Please try again in a moment.'
      })
    };
  }
};
